#!/usr/bin/env ruby

require "bundler"
Bundler.require :default, :development

QUERY = "SELECT * FROM traffic_exports LIMIT 9000"
LOGIN = {
  "host" => "localhost",
  "port" => 50000,
  "database" => "test_drive",
  "username" => "monetdb",
  "password" => "monetdb"
}

MonetDB.establish_connection LOGIN

def select
  MonetDB.connection.select_rows QUERY
end

puts "Loading MonetDB development environment (#{MonetDB::VERSION})"
Pry.start
