#!/usr/bin/env ruby

require "bundler"
Bundler.require :default, :development

QUERY = "SELECT * FROM stats LIMIT 2000"
LOGIN = {
  "host" => "localhost",
  "port" => 50000,
  "database" => "my_monetdb",
  "username" => "monetdb",
  "password" => "monetdb"
}

MonetDB.establish_connection LOGIN

def query
  MonetDB.connection.query QUERY
end

puts "Loading MonetDB development environment (#{MonetDB::VERSION})"
Pry.start
